title: Sounds
description: A collection of markdown articles
markdown: kramdown

remote_theme: "jekyll/minima"
minima:
  skin: solarized

# Optional settings to ensure proper linking
baseurl: "/sounds"
