title: Sounds
description: A collection of markdown articles
markdown: kramdown

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Optional settings to ensure proper linking
baseurl: "/sounds"
